<div class="cl-panel flex h-full min-h-0 flex-col overflow-hidden">
 <div class="cl-panel-header"><div><p class="cl-panel-eyebrow">Verification · Validation · Evidence</p><h2 class="cl-panel-title">Test Runs & Validation</h2></div><div class="flex gap-2"><button id="tmNewRun" class="cl-button cl-button-primary">+ Test Run</button><button id="tmRefresh" class="cl-button cl-button-secondary">Aktualisieren</button></div></div>
 <div class="grid shrink-0 grid-cols-3 gap-3 border-b bg-slate-50 p-4"><div class="cl-kpi"><div class="cl-kpi-label">Kriterien</div><div id="tmTotal" class="cl-kpi-value">0</div></div><div class="cl-kpi border-l-emerald-500"><div class="cl-kpi-label">Validiert</div><div id="tmValidated" class="cl-kpi-value text-emerald-700">0</div></div><div class="cl-kpi border-l-blue-500"><div class="cl-kpi-label">Coverage</div><div id="tmCoverage" class="cl-kpi-value">0%</div></div></div>
 <div class="flex shrink-0 border-b"><button data-tm-tab="runs" class="border-b-2 border-blue-900 px-5 py-3 font-bold text-blue-900">Test Runs</button><button data-tm-tab="links" class="border-b-2 border-transparent px-5 py-3 font-semibold">Vorhandene Traceability</button></div>
 <div id="tmRunsView" class="grid min-h-0 flex-1 grid-cols-[340px_minmax(0,1fr)]"><aside class="overflow-y-auto border-r bg-slate-50 p-3"><div id="tmRunList" class="space-y-2"></div></aside><section class="overflow-y-auto p-5"><div id="tmRunDetail" class="cl-empty-state">Test Run auswählen.</div></section></div>
 <div id="tmLinksView" class="hidden min-h-0 flex-1 overflow-y-auto bg-slate-50 p-5"><div class="mx-auto max-w-5xl"><div class="mb-4 rounded border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">Die Verbindungen stammen direkt aus dem Document Studio. Hier muss nichts erneut verknüpft werden.</div><div id="tmLinkList" class="space-y-2"></div></div></div>
</div>
<div id="tmCreateModal" class="cl-modal-overlay hidden"><form id="tmCreateForm" class="mx-auto flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded bg-white shadow-2xl"><div class="cl-modal-header"><div><p class="cl-panel-eyebrow">Testausführung</p><h2 class="cl-modal-title">Neuen Test Run erzeugen</h2></div><button type="button" data-tm-close class="cl-button cl-button-secondary">✕</button></div><div class="cl-modal-body space-y-4"><label class="cl-label">Testfall<select id="tmCreateCase" required class="cl-select"></select></label><label class="cl-label">Titel<input id="tmCreateTitle" class="cl-input"></label><div class="grid gap-4 md:grid-cols-2"><label class="cl-label">Software-Version<input id="tmCreateSoftware" class="cl-input"></label><label class="cl-label">Hardware-Revision<input id="tmCreateHardware" class="cl-input"></label></div><label class="cl-label">Testumgebung<textarea id="tmCreateEnvironment" class="cl-textarea"></textarea></label></div><div class="cl-modal-footer"><button type="button" data-tm-close class="cl-button cl-button-secondary">Abbrechen</button><button class="cl-button cl-button-primary">Test Run erstellen</button></div></form></div>
<div id="tmEditModal" class="cl-modal-overlay hidden"><form id="tmEditForm" class="mx-auto flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded bg-white shadow-2xl"><div class="cl-modal-header"><div><p class="cl-panel-eyebrow">Test Run</p><h2 class="cl-modal-title">Stammdaten bearbeiten</h2></div><button type="button" data-tm-edit-close class="cl-button cl-button-secondary">✕</button></div><div class="cl-modal-body space-y-4"><label class="cl-label">Titel<input id="tmEditTitle" required class="cl-input"></label><div class="grid gap-4 md:grid-cols-2"><label class="cl-label">Software-Version<input id="tmEditSoftware" class="cl-input"></label><label class="cl-label">Hardware-Revision<input id="tmEditHardware" class="cl-input"></label></div><label class="cl-label">Testumgebung<textarea id="tmEditEnvironment" class="cl-textarea"></textarea></label></div><div class="cl-modal-footer"><button type="button" data-tm-edit-close class="cl-button cl-button-secondary">Abbrechen</button><button class="cl-button cl-button-primary">Änderungen speichern</button></div></form></div>
