import { currentProjectId } from './state.js';
let attachmentItems=[];
let attachmentContext=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeLabels={requirement:'Anforderung',use_case:'Use Case',task:'Aufgabe',issue:'Issue',milestone:'Meilenstein',asset:'Asset',risk:'Risiko',user_story:'User Story'};
export async function loadAttachments(){const list=document.getElementById('attachmentList');if(!list)return;if(!currentProjectId){attachmentItems=[];list.innerHTML='<div class="cl-empty-state">Bitte zuerst ein Projekt auswählen.</div>';return;}try{const r=await fetch(`../api/get_attachments.php?project_id=${encodeURIComponent(currentProjectId)}`);const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Anhänge konnten nicht geladen werden.');attachmentItems=d.attachments||[];fillCategoryFilter();renderAttachments();}catch(e){list.innerHTML=`<div class="cl-empty-state text-red-600">${esc(e.message)}</div>`;}}
function fillCategoryFilter(){const s=document.getElementById('attachmentCategoryFilter');if(!s)return;const old=s.value;const cats=[...new Set(attachmentItems.map(x=>x.category).filter(Boolean))].sort();s.innerHTML='<option value="">Alle Kategorien</option>'+cats.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');s.value=old;}
function renderAttachments(){const list=document.getElementById('attachmentList');if(!list)return;const q=(document.getElementById('attachmentSearch')?.value||'').toLowerCase();const cat=document.getElementById('attachmentCategoryFilter')?.value||'';const rows=attachmentItems.filter(a=>{const text=[a.attachment_key,a.title,a.category,a.description,a.original_filename,a.relative_path,...(a.links||[]).flatMap(l=>[l.entity_key,l.entity_title])].filter(Boolean).join(' ').toLowerCase();return(!cat||a.category===cat)&&(!q||text.includes(q));});if(!rows.length){list.innerHTML='<div class="cl-empty-state">Keine passenden Anhänge gefunden.</div>';return;}list.innerHTML=`<div class="grid grid-cols-1 gap-3 xl:grid-cols-2">${rows.map(card).join('')}</div>`;}
function card(a){const links=(a.links||[]).map(l=>`<span class="rounded border border-slate-300 bg-slate-100 px-2 py-0.5 text-[10px] font-bold">${esc(typeLabels[l.entity_type]||l.entity_type)}: ${esc(l.entity_key||l.entity_id)}</span>`).join('');const action=a.storage_type==='upload'?`<a href="${esc(a.download_url)}" target="_blank" class="cl-button cl-button-secondary">Öffnen</a>`:`<button type="button" data-copy-path="${esc(a.relative_path)}" class="cl-button cl-button-secondary">Pfad kopieren</button>`;const preview=a.is_image?`<a href="${esc(a.download_url)}" target="_blank"><img src="${esc(a.download_url)}" class="h-28 w-full rounded border border-slate-200 object-contain bg-white" alt="${esc(a.title)}"></a>`:'';return `<article class="rounded border border-slate-300 bg-white p-4 shadow-sm">${preview}<div class="mt-2 flex justify-between gap-3"><div><div class="font-mono text-xs font-bold text-blue-900">${esc(a.attachment_key)}</div><h3 class="font-extrabold text-slate-900">${esc(a.title)}</h3><div class="text-xs text-slate-500">${esc(a.category)} · ${esc(a.version_label||'ohne Version')} · ${esc(a.status)}</div></div><div class="flex items-start gap-2">${action}<button type="button" data-delete-attachment="${a.id}" class="cl-button cl-button-secondary text-red-600">Löschen</button></div></div><p class="mt-2 text-sm text-slate-600">${esc(a.description||a.original_filename||a.relative_path||'')}</p><div class="mt-3 flex flex-wrap gap-1">${links||'<span class="text-xs italic text-slate-400">Noch nicht verknüpft</span>'}</div></article>`;}
function openAttachment(context=null){if(!currentProjectId)return alert('Bitte zuerst ein Projekt auswählen.');attachmentContext=context;const f=document.getElementById('attachmentForm');f?.reset();document.getElementById('attachmentFileBox')?.classList.remove('hidden');document.getElementById('attachmentPathBox')?.classList.add('hidden');const box=document.getElementById('attachmentContext');if(context&&box){box.classList.remove('hidden');box.innerHTML=`Wird verknüpft mit <strong>${esc(typeLabels[context.entity_type]||context.entity_type)} ${esc(context.entity_key||context.entity_id)}</strong><br>${esc(context.entity_title||'')}`;}else box?.classList.add('hidden');const modal=document.getElementById('attachmentModal');modal?.classList.remove('hidden');modal?.classList.add('flex');}
function closeAttachment(){const m=document.getElementById('attachmentModal');m?.classList.add('hidden');m?.classList.remove('flex');}
async function saveAttachment(e){e.preventDefault();const fd=new FormData(e.currentTarget);fd.append('project_id',currentProjectId);if(attachmentContext)Object.entries(attachmentContext).forEach(([k,v])=>fd.append(k,v??''));const b=e.submitter;b.disabled=true;try{const r=await fetch('../api/set_attachment.php',{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Speichern fehlgeschlagen.');closeAttachment();await loadAttachments();if(attachmentContext)document.dispatchEvent(new CustomEvent('captainslog:attachments-changed',{detail:attachmentContext}));}catch(err){alert('Fehler: '+err.message);}finally{b.disabled=false;}}
export function initAttachmentEvents(){document.getElementById('btnNewAttachment')?.addEventListener('click',()=>openAttachment());document.getElementById('attachmentClose')?.addEventListener('click',closeAttachment);document.getElementById('attachmentCancel')?.addEventListener('click',closeAttachment);document.getElementById('attachmentSearch')?.addEventListener('input',renderAttachments);document.getElementById('attachmentCategoryFilter')?.addEventListener('change',renderAttachments);document.getElementById('attachmentForm')?.addEventListener('submit',saveAttachment);document.querySelectorAll('input[name="storage_type"]').forEach(r=>r.addEventListener('change',()=>{const upload=r.value==='upload'&&r.checked;document.getElementById('attachmentFileBox')?.classList.toggle('hidden',!upload);document.getElementById('attachmentPathBox')?.classList.toggle('hidden',upload);}));document.getElementById('attachmentList')?.addEventListener('click',async e=>{const copy=e.target.closest('[data-copy-path]');if(copy){await navigator.clipboard.writeText(copy.dataset.copyPath);copy.textContent='Kopiert';}const del=e.target.closest('[data-delete-attachment]');if(del&&confirm('Anhang wirklich löschen?')){const r=await fetch('../api/delete_attachment.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:Number(del.dataset.deleteAttachment),project_id:currentProjectId})});const d=await r.json();if(d.success)loadAttachments();else alert(d.error);}});}
window.openAttachmentModal=(entity_type,entity_id,entity_key='',entity_title='')=>openAttachment({entity_type,entity_id,entity_key,entity_title});
