import { currentProjectId } from './state.js';
let data={test_cases:[],requirements:[],links:[]},selected=null,ready=false;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function initTestManagementEvents(){if(ready)return;ready=true;$('tmSearch')?.addEventListener('input',renderTcs);$('tmCriterionSearch')?.addEventListener('input',renderCriteria);$('tmTypeFilter')?.addEventListener('change',renderCriteria);$('tmSave')?.addEventListener('click',save);}
export async function loadTestManagement(){if(!currentProjectId)return;try{const r=await fetch(`../api/get_test_management.php?project_id=${encodeURIComponent(currentProjectId)}&t=${Date.now()}`),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Laden fehlgeschlagen');data=d;$('tmTcCount').textContent=data.test_cases.length;$('tmLinkCount').textContent=data.links.length;renderTcs();if(selected)selectTc(selected);}catch(e){$('tmTestCaseList').innerHTML=`<div class="m-4 bg-red-50 p-3 text-red-700">${esc(e.message)}</div>`;}}
function renderTcs(){const q=($('tmSearch')?.value||'').toLowerCase(),items=data.test_cases.filter(x=>!q||`${x.req_key} ${x.title}`.toLowerCase().includes(q));$('tmTestCaseList').innerHTML=items.map(x=>{const n=data.links.filter(l=>+l.test_case_id===+x.id).length;return `<button class="tm-tc w-full border-b p-4 text-left hover:bg-blue-50 ${+selected===+x.id?'bg-blue-50':''}" data-id="${x.id}"><b class="font-mono text-blue-900">${esc(x.req_key)}</b><span class="block truncate text-sm font-semibold">${esc(x.title)}</span><small class="text-slate-500">${n} Kriterien</small></button>`}).join('')||'<div class="cl-empty-state m-4">Keine Test Cases.</div>';document.querySelectorAll('.tm-tc').forEach(b=>b.onclick=()=>selectTc(+b.dataset.id));}
function selectTc(id){selected=+id;const tc=data.test_cases.find(x=>+x.id===selected);if(!tc)return;$('tmEmpty').classList.add('hidden');$('tmEditor').classList.remove('hidden');$('tmEditor').classList.add('flex');$('tmSelectedKey').textContent=tc.req_key;$('tmSelectedTitle').textContent=tc.title;$('tmSelectedDescription').textContent=tc.description||'Keine Beschreibung.';renderTcs();renderCriteria();}
function linked(r,i){return data.links.some(l=>+l.test_case_id===selected&&+l.requirement_id===+r&&+l.criterion_index===+i)}
function renderCriteria(){if(!selected)return;const q=($('tmCriterionSearch')?.value||'').toLowerCase(),type=$('tmTypeFilter')?.value||'';const reqs=data.requirements.filter(r=>(!type||r.type===type)&&(!q||`${r.req_key} ${r.title} ${r.criteria.map(c=>c.text).join(' ')}`.toLowerCase().includes(q)));$('tmCriteria').innerHTML=reqs.map(r=>`<section class="mb-4 overflow-hidden rounded border"><header class="border-b bg-slate-50 px-4 py-3"><b class="font-mono text-blue-900">${esc(r.req_key)}</b> <span class="font-semibold">${esc(r.title)}</span></header>${r.criteria.map(c=>`<label class="flex cursor-pointer gap-3 border-b px-4 py-3 last:border-0 hover:bg-blue-50"><input class="tm-criterion mt-1" type="checkbox" data-r="${r.id}" data-i="${c.index}" ${linked(r.id,c.index)?'checked':''}><span>${esc(c.text)}</span></label>`).join('')}</section>`).join('')||'<div class="cl-empty-state">Keine Kriterien gefunden.</div>';}
async function save(){const criteria=[...document.querySelectorAll('.tm-criterion:checked')].map(x=>({requirement_id:+x.dataset.r,criterion_index:+x.dataset.i})),b=$('tmSave');b.disabled=true;try{const r=await fetch('../api/set_test_case_criteria.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:currentProjectId,test_case_id:selected,criteria})}),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Speichern fehlgeschlagen');await loadTestManagement();alert(`${d.saved} Zuordnungen gespeichert.`);}catch(e){alert('Fehler: '+e.message)}finally{b.disabled=false}}
