<?php
require_once __DIR__.'/document_studio_common.php';uid();try{$pid=trim((string)($_GET['project_id']??''));$type=$_GET['type']??'';project($pdo,$pid);$rows=[];
if($type==='risk'){$q=$pdo->prepare("SELECT id,requirement_key item_key,title,status,'document' source_type FROM requirement_documents WHERE project_id=? AND requirement_type='RISK' ORDER BY requirement_key");$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
elseif($type==='issue'){$q=$pdo->prepare('SELECT id,issue_key item_key,title,status FROM issues WHERE project_id=? ORDER BY issue_key');$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
elseif($type==='task'){$q=$pdo->prepare("SELECT id,COALESCE(wbs_code,CAST(id AS CHAR))item_key,title,CONCAT(progress_pct,'%')status FROM project_tasks WHERE project_id=? AND parent_id IS NULL ORDER BY wbs_code,id");$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
elseif($type==='person'){$q=$pdo->prepare("SELECT u.id,CAST(u.id AS CHAR)item_key,u.username title,COALESCE(pm.project_role,'Team')status FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.project_id=? AND pm.is_active=1 ORDER BY u.username");$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
elseif($type==='test_case'){$q=$pdo->prepare("SELECT id,requirement_key item_key,title,status,'document' source_type,'not_run' test_result FROM requirement_documents WHERE project_id=? AND requirement_type IN('TC','TEST','TST') ORDER BY requirement_key");$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
elseif($type==='test_run'){$q=$pdo->prepare("SELECT id,requirement_key item_key,title,status,'document_run' source_type,COALESCE(JSON_UNQUOTE(JSON_EXTRACT(metadata,'$.test_result')),'not_run')test_result FROM requirement_documents WHERE project_id=? AND requirement_type='TR' ORDER BY updated_at DESC,requirement_key");$q->execute([$pid]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);}
else out(['success'=>false,'error'=>'Unbekannter Katalog.'],422);out(['success'=>true,'items'=>$rows]);}catch(Throwable$e){out(['success'=>false,'error'=>$e->getMessage()],500);}
