<?php
ini_set('display_errors',0);error_reporting(E_ALL);session_start();require '../config/db.php';header('Content-Type: application/json; charset=utf-8');
try{require_edit_permission();$d=json_decode(file_get_contents('php://input'),true)?:[];$project=$d['project_id']??'';$rows=$d['rows']??[];$filename=basename($d['filename']??'Excel-Import.xlsx');$sheet=$d['sheet_name']??'Tabelle';$hash=$d['file_hash']??hash('sha256',json_encode($rows));$uid=$_SESSION['user_id']??0;
if(!$project||!is_array($rows)||!$uid)throw new Exception('Importdaten fehlen.');$a=$pdo->prepare('SELECT 1 FROM project_members WHERE project_id=? AND user_id=?');$a->execute([$project,$uid]);if(!$a->fetchColumn())throw new Exception('Kein Projektzugriff.');
$pdo->beginTransaction();$next=$pdo->prepare("SELECT COALESCE(MAX(CAST(SUBSTRING_INDEX(issue_key,'-',-1) AS UNSIGNED)),0) FROM issues WHERE project_id=?");$next->execute([$project]);$counter=(int)$next->fetchColumn();
$ins=$pdo->prepare('INSERT IGNORE INTO issues(project_id,issue_key,external_id,issue_type,title,description,status,priority,severity,category,external_assignee,reported_at,external_response,internal_response,source_type,source_document,source_sheet,source_row,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$ok=0;$skip=0;
$statusMap=['open'=>'open','in progress'=>'in_progress','waiting for response'=>'waiting_response','ready for test'=>'ready_for_test','approved'=>'approved','closed'=>'closed'];
foreach($rows as $idx=>$r){$title=trim((string)($r['title']??''));if($title===''||preg_match('/^(fehler|#)$/i',$title)){$skip++;continue;}$counter++;$raw=strtolower(trim((string)($r['status']??'open')));$status=$statusMap[$raw]??'open';$date=$r['reported_at']??null;if($date && preg_match('/^(\d{1,2})[\.\/](\d{1,2})[\.\/](\d{2,4})$/',$date,$m)){$y=(int)$m[3];if($y<100)$y+=2000;$date=sprintf('%04d-%02d-%02d',$y,$m[2],$m[1]);}
$ins->execute([$project,'ISSUE-'.str_pad((string)$counter,3,'0',STR_PAD_LEFT),$r['external_id']??null,'bug',$title,$r['description']??null,$status,'medium','medium',$r['category']??null,$r['assignee']??null,$date?:null,$r['external_response']??null,$r['internal_response']??null,'excel',$filename,$sheet,(int)($r['source_row']??($idx+1)),$uid]);if($ins->rowCount())$ok++;else $skip++;}
$log=json_encode(['imported'=>$ok,'skipped'=>$skip],JSON_UNESCAPED_UNICODE);$imp=$pdo->prepare('INSERT INTO issue_imports(project_id,original_filename,file_hash,sheet_name,imported_rows,skipped_rows,import_status,import_log,imported_by) VALUES(?,?,?,?,?,?,?, ?,?) ON DUPLICATE KEY UPDATE imported_rows=VALUES(imported_rows),skipped_rows=VALUES(skipped_rows),import_status=VALUES(import_status),import_log=VALUES(import_log)');$imp->execute([$project,$filename,$hash,$sheet,$ok,$skip,'completed',$log,$uid]);$pdo->commit();echo json_encode(['success'=>true,'imported'=>$ok,'skipped'=>$skip]);}
catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();http_response_code(400);echo json_encode(['success'=>false,'error'=>$e->getMessage()]);}
