<?php
declare(strict_types=1);
require_once __DIR__.'/document_studio_common.php';
require_once __DIR__.'/criterion_traceability_lib.php';
$userId=uid();
function trBlock(PDO $p,string $runId):array{$q=$p->prepare("SELECT id,content FROM requirement_document_blocks WHERE document_id=? AND block_type='testRunExecution' ORDER BY sort_order,id LIMIT 1");$q->execute([$runId]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new RuntimeException('Test-Run-Daten fehlen.');$r['data']=json_decode($r['content']??'{}',true)?:[];return$r;}
function trSaveBlock(PDO $p,array $b,array $data):void{$p->prepare('UPDATE requirement_document_blocks SET content=? WHERE id=?')->execute([json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$b['id']]);}
function trCriteria(PDO $p,string $docId):array{$q=$p->prepare("SELECT content FROM requirement_document_blocks WHERE document_id=? AND block_type='acceptanceCriteria' ORDER BY sort_order,id");$q->execute([$docId]);$out=[];foreach($q->fetchAll(PDO::FETCH_COLUMN)as$json){$d=json_decode((string)$json,true)?:[];foreach(($d['items']??[])as$c){$text=trim(strip_tags((string)($c['text']??'')));if(!empty($c['id'])&&$text!=='')$out[]=['criterion_id'=>(string)$c['id'],'criterion_revision'=>max(1,(int)($c['revision']??1)),'text'=>(string)$c['text'],'result'=>'not_run','comment'=>'','code_reference'=>'','file_ids'=>[]];}}return$out;}
function trSummary(PDO $p,string $project):array{$q=$p->prepare("SELECT COALESCE(SUM(s.leaf_count),0)t,COALESCE(SUM(s.passed_count),0)v FROM document_verification_snapshots s JOIN requirement_documents d ON d.id=s.document_id WHERE d.project_id=? AND d.requirement_type<>'TR'");$q->execute([$project]);$r=$q->fetch(PDO::FETCH_ASSOC)?:['t'=>0,'v'=>0];$t=(int)$r['t'];$v=(int)$r['v'];return['total'=>$t,'validated'=>$v,'coverage'=>$t?round($v*100/$t,2):0];}
function trRemoveEvidence(PDO $p,string $runId):void{$q=$p->prepare('DELETE e FROM document_criterion_evidence e JOIN document_test_links l ON l.id=e.document_test_link_id WHERE l.test_run_id=?');$q->execute([$runId]);$p->prepare('DELETE FROM document_test_links WHERE test_run_id=?')->execute([$runId]);}
function trResult(array $items):string{$r=array_column($items,'result');return in_array('failed',$r,true)?'failed':(in_array('blocked',$r,true)?'blocked':'passed');}
try{$m=$_SERVER['REQUEST_METHOD'];$a=(string)($_GET['action']??'list');
if($m==='GET'&&$a==='catalog'){$project=trim((string)($_GET['project_id']??''));project($pdo,$project);$q=$pdo->prepare("SELECT d.id,d.requirement_key,d.title FROM requirement_documents d WHERE d.project_id=? AND d.requirement_type IN('TC','TEST','TST') ORDER BY d.requirement_key");$q->execute([$project]);out(['success'=>true,'test_cases'=>$q->fetchAll(PDO::FETCH_ASSOC),'summary'=>trSummary($pdo,$project)]);}
if($m==='GET'&&$a==='list'){$project=trim((string)($_GET['project_id']??''));project($pdo,$project);$q=$pdo->prepare("SELECT id,requirement_key run_key,title,status,metadata,updated_at FROM requirement_documents WHERE project_id=? AND requirement_type='TR' ORDER BY updated_at DESC");$q->execute([$project]);$runs=[];foreach($q->fetchAll(PDO::FETCH_ASSOC)as$r){$x=json_decode($r['metadata']??'{}',true)?:[];$r['test_result']=$x['test_result']??'draft';$r['test_case_key']=$x['test_case_key']??'';$runs[]=$r;}out(['success'=>true,'runs'=>$runs,'summary'=>trSummary($pdo,$project)]);}
if($m==='GET'&&$a==='detail'){$id=trim((string)($_GET['id']??''));$d=doc($pdo,$id);if($d['requirement_type']!=='TR')throw new RuntimeException('Kein Test Run.');$b=trBlock($pdo,$id);out(['success'=>true,'run'=>$d,'data'=>$b['data'],'metadata'=>json_decode($d['metadata']??'{}',true)?:[]]);}
if($m==='GET'&&$a==='links'){$project=trim((string)($_GET['project_id']??''));$q=$pdo->prepare("SELECT l.id,cd.requirement_key child_key,pd.requirement_key parent_key,l.child_criterion_id,l.parent_criterion_id,l.aggregation_rule FROM document_criterion_links l JOIN requirement_documents cd ON cd.id=l.child_document_id JOIN requirement_documents pd ON pd.id=l.parent_document_id WHERE l.project_id=? ORDER BY cd.requirement_key,pd.requirement_key");$q->execute([$project]);out(['success'=>true,'links'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
if($m==='POST'&&$a==='create'){$x=body();$project=trim((string)($x['project_id']??''));$tcId=trim((string)($x['test_case_id']??''));$tc=doc($pdo,$tcId);if($tc['project_id']!==$project||!in_array($tc['requirement_type'],['TC','TEST','TST'],true))throw new RuntimeException('Testfall ist ungültig.');$items=trCriteria($pdo,$tcId);if(!$items)throw new RuntimeException($tc['requirement_key'].' besitzt keine ausführbaren Akzeptanzkriterien.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO requirement_document_sequences(project_id,requirement_type,last_number)VALUES(?,'TR',1)ON DUPLICATE KEY UPDATE last_number=last_number+1")->execute([$project]);$q=$pdo->prepare("SELECT last_number FROM requirement_document_sequences WHERE project_id=? AND requirement_type='TR' FOR UPDATE");$q->execute([$project]);$key='TR-'.str_pad((string)$q->fetchColumn(),3,'0',STR_PAD_LEFT);$id=uuid4();$title=trim((string)($x['title']??''))?:('Test Run '.$tc['requirement_key']);$meta=['test_result'=>'draft','test_case_id'=>$tcId,'test_case_key'=>$tc['requirement_key'],'software_version'=>$x['software_version']??'','hardware_revision'=>$x['hardware_revision']??'','test_environment'=>$x['test_environment']??''];$q=$pdo->prepare("INSERT INTO requirement_documents(id,project_id,requirement_key,requirement_type,title,status,priority,relevance,review_status,metadata,created_by,updated_by)VALUES(?,?,?,?,?,'Open','Medium','Must','New',?,?,?)");$q->execute([$id,$project,$key,'TR',$title,json_encode($meta,JSON_UNESCAPED_UNICODE),$userId,$userId]);$content=['test_case_id'=>$tcId,'test_case_key'=>$tc['requirement_key'],'items'=>$items,'confirmed'=>false];$pdo->prepare("INSERT INTO requirement_document_blocks(id,document_id,block_type,content,sort_order)VALUES(?,?,'testRunExecution',?,0)")->execute([uuid4(),$id,json_encode($content,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$pdo->commit();out(['success'=>true,'run_id'=>$id,'run_key'=>$key],201);}
if($m==='POST'&&$a==='update'){$x=body();$id=trim((string)($x['run_id']??''));$d=doc($pdo,$id);if($d['requirement_type']!=='TR')throw new RuntimeException('Kein Test Run.');$meta=json_decode($d['metadata']??'{}',true)?:[];foreach(['software_version','hardware_revision','test_environment']as$k)$meta[$k]=trim((string)($x[$k]??$meta[$k]??''));$title=trim((string)($x['title']??$d['title']));if($title==='')throw new RuntimeException('Titel fehlt.');$pdo->prepare('UPDATE requirement_documents SET title=?,metadata=?,updated_by=? WHERE id=?')->execute([$title,json_encode($meta,JSON_UNESCAPED_UNICODE),$userId,$id]);out(['success'=>true]);}
if($m==='POST'&&$a==='item'){$x=body();$id=trim((string)($x['run_id']??''));$cid=trim((string)($x['criterion_id']??''));$b=trBlock($pdo,$id);$d=$b['data'];if(!empty($d['confirmed']))throw new RuntimeException('Test Run zuerst wieder öffnen.');$found=false;foreach($d['items']as&$i)if((string)$i['criterion_id']===$cid){$result=(string)($x['result']??'not_run');if(!in_array($result,['not_run','passed','failed','blocked'],true))throw new RuntimeException('Ungültiges Ergebnis.');$i['result']=$result;$i['comment']=trim((string)($x['comment']??''));$i['code_reference']=trim((string)($x['code_reference']??''));$i['file_ids']=array_values(array_unique(array_merge($i['file_ids']??[],array_filter(array_map('strval',$x['file_ids']??[])))));$found=true;break;}unset($i);if(!$found)throw new RuntimeException('Kriterium nicht gefunden.');trSaveBlock($pdo,$b,$d);out(['success'=>true]);}
if($m==='POST'&&$a==='confirm'){$x=body();$id=trim((string)($x['run_id']??''));$run=doc($pdo,$id);$b=trBlock($pdo,$id);$d=$b['data'];if(!empty($d['confirmed']))throw new RuntimeException('Bereits bestätigt.');$items=$d['items']??[];foreach($items as$i){if(($i['result']??'not_run')==='not_run')throw new RuntimeException('Alle Kriterien müssen bewertet werden.');if(trim((string)($i['comment']??''))==='')throw new RuntimeException('Jedes Kriterium benötigt einen Kommentar.');if(trim((string)($i['code_reference']??''))===''&&empty($i['file_ids']))throw new RuntimeException('Jedes Kriterium benötigt Code-Referenz oder Datei/Bild.');}$tcId=(string)$d['test_case_id'];$tc=doc($pdo,$tcId);$pdo->beginTransaction();foreach($items as$i){$link=uuid4();$md=['label'=>$run['requirement_key'].' '.$run['title'],'comment'=>$i['comment'],'code_reference'=>$i['code_reference'],'file_ids'=>$i['file_ids'],'source_document_id'=>$id];$pdo->prepare('INSERT INTO document_test_links(id,project_id,document_id,test_case_id,test_run_id,document_revision,link_type,result,executed_at,metadata,created_by)VALUES(?,?,?,?,?,?,?,?,NOW(),?,?)')->execute([$link,$run['project_id'],$tcId,$tcId,$id,(int)$tc['revision'],'validates',$i['result'],json_encode($md,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$userId]);$pdo->prepare('INSERT INTO document_criterion_evidence(id,project_id,document_id,criterion_id,criterion_revision,document_test_link_id,result,created_by)VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE criterion_revision=VALUES(criterion_revision),result=VALUES(result),updated_at=CURRENT_TIMESTAMP')->execute([uuid4(),$run['project_id'],$tcId,$i['criterion_id'],(int)$i['criterion_revision'],$link,$i['result'],$userId]);}$status=trResult($items);$d['confirmed']=true;$d['confirmed_at']=date('Y-m-d H:i:s');trSaveBlock($pdo,$b,$d);$meta=json_decode($run['metadata']??'{}',true)?:[];$meta['test_result']=$status;$pdo->prepare('UPDATE requirement_documents SET status=?,review_status=?,metadata=?,updated_by=? WHERE id=?')->execute([$status==='passed'?'Closed':'In Progress',$status==='passed'?'Approved':'In Review',json_encode($meta,JSON_UNESCAPED_UNICODE),$userId,$id]);ctRecalculate($pdo,$tcId);$pdo->commit();out(['success'=>true,'status'=>$status,'summary'=>trSummary($pdo,$run['project_id'])]);}
if($m==='POST'&&$a==='reopen'){$x=body();$id=trim((string)($x['run_id']??''));$run=doc($pdo,$id);$b=trBlock($pdo,$id);$d=$b['data'];$tcId=(string)$d['test_case_id'];$pdo->beginTransaction();trRemoveEvidence($pdo,$id);$d['confirmed']=false;unset($d['confirmed_at']);trSaveBlock($pdo,$b,$d);$meta=json_decode($run['metadata']??'{}',true)?:[];$meta['test_result']='draft';$pdo->prepare("UPDATE requirement_documents SET status='Open',review_status='New',metadata=?,updated_by=? WHERE id=?")->execute([json_encode($meta,JSON_UNESCAPED_UNICODE),$userId,$id]);ctRecalculate($pdo,$tcId);$pdo->commit();out(['success'=>true,'summary'=>trSummary($pdo,$run['project_id'])]);}
if($m==='DELETE'&&$a==='delete'){$x=body();$id=trim((string)($x['run_id']??''));$run=doc($pdo,$id);$b=trBlock($pdo,$id);$tcId=(string)($b['data']['test_case_id']??'');$pdo->beginTransaction();trRemoveEvidence($pdo,$id);$q=$pdo->prepare('SELECT relative_path FROM requirement_document_files WHERE document_id=?');$q->execute([$id]);foreach($q->fetchAll(PDO::FETCH_COLUMN)as$rel){$path=realpath(__DIR__.'/../'.$rel);$base=realpath(__DIR__.'/../uploads/documents');if($path&&$base&&str_starts_with($path,$base.DIRECTORY_SEPARATOR)&&is_file($path))@unlink($path);}$pdo->prepare('DELETE FROM requirement_document_files WHERE document_id=?')->execute([$id]);$pdo->prepare('DELETE FROM requirement_document_blocks WHERE document_id=?')->execute([$id]);$pdo->prepare('DELETE FROM requirement_documents WHERE id=?')->execute([$id]);if($tcId!=='')ctRecalculate($pdo,$tcId);$pdo->commit();out(['success'=>true,'summary'=>trSummary($pdo,$run['project_id'])]);}
out(['success'=>false,'error'=>'Methode nicht erlaubt.'],405);}catch(Throwable$e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();out(['success'=>false,'error'=>$e->getMessage()],400);}
